IBM SCIS use case
ot4i/app-connect-templates pull request #168
Opened 2021-07-27 11:56 UTC by shahminiaru

Use case for IBM Supply Chain Intelligence Suite

2021-07-28 08:01 UTC, AnimatIan commented on resources/Orders ingestion to IBM Supply Chain Intelligence Suite from Microsoft Dynamics 365.yaml
> +      account-name: Account 3
Should remove account definitions, as per guidance:
"Important: Make sure that you delete all account-name elements from the file either before or after you upload the file. (That will then force users to connect to their own accounts.)"
See https://github.ibm.com/Cloud-Integration/appconnect-wiki/wiki/Authoring-App-Connect-templates

2021-07-28 08:01 UTC, AnimatIan requested changes
Remove account definitions, as per guidance:
"Important: Make sure that you delete all account-name elements from the file either before or after you upload the file. (That will then force users to connect to their own accounts.)"
See https://github.ibm.com/Cloud-Integration/appconnect-wiki/wiki/Authoring-App-Connect-templates

2021-07-28 08:29 UTC, AnimatIan approved these changes

2021-07-28 14:28 UTC, CamK submitted a review, later dismissed

2021-07-28 15:01 UTC, AnimatIan approved these changes

2021-07-29 10:26 UTC, merged

2021-07-29 10:26 UTC, AnimatIan commented
Merging while travis checks not working