coupa shahminiaru
ot4i/app-connect-templates pull request #272
Opened 2023-01-05 07:57 UTC by shahminiaru

UC1 -Create a supplier and invoice in Coupa for each purchase order retrieved from IBM Maximo

Note: Imported the flow without any issue on PSL local sandbox.
![image](https://user-images.githubusercontent.com/86762255/210729867-5b1a3f9b-770e-4487-836e-c6fd64480229.png)

2023-02-15 16:10 UTC, AnimatIan requested changes
The links to the instructions in Github don't work. I think that they need to start with https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/ before the _instructions.md filename.
Please change the links in the _instructions.md files.

2023-02-15 16:14 UTC, AnimatIan reviewed
_instructions MD file includes an HTML </br> tag. Please replace this with markdown.

2023-02-16 14:39 UTC, shahminiaru commented
Updated. 
- updated to include https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/
- removed the html tags

2023-02-20 16:58 UTC, AnimatIan approved these changes

2023-02-20 17:01 UTC, AnimatIan approved these changes

2023-02-20 17:01 UTC, merged