MS OneDrive shahminiaru (master)
ot4i/app-connect-templates pull request #275
Opened 2023-01-11 12:11 UTC by shahminiaru

Microsoft OneDrive for Business Use cases:
- Create a file in Microsoft OneDrive for Business and a Zendesk ticket whenever a Gmail message is received 
- Sync Jira issue attachments with Microsoft OneDrive for Business

Note: Imported the flows without any issue on PSL local sandbox.

2023-02-15 16:05 UTC, AnimatIan requested changes
The links to the instructions in Github don't work. I think that they need to start with https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/ before the _instructions.md filename.
Please change the links in the _instructions.md files.

2023-02-16 14:41 UTC, shahminiaru reviewed
Updated. 
- updated to include https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/

2023-02-20 17:06 UTC, AnimatIan submitted a review, later dismissed

2023-02-20 17:11 UTC, AnimatIan approved these changes

2023-02-20 17:11 UTC, merged