Salesforce shahminiaru (master)
ot4i/app-connect-templates pull request #277
Opened 2023-01-13 07:03 UTC by shahminiaru

Salesforce UC: Retrieve campaign records from Salesforce and update the rows of the Microsoft Excel Online worksheet with the campaign details

Note: Imported the flows without any issue on PSL local sandbox.

2023-01-19 06:56 UTC, shahminiaru commented
The npm test failed because the Title string is too long in template metadata. 
```
1) Template Metadata
       is valid against the given schema:
     AssertionError: expected value to match json-schema 'IBM App Connect Template Gallery metadata schema' -> '{"templates":[{"name":"Sync ne...'
      String is too long (146 chars), maximum 120
          schema: IBM App Connect Template Gallery metadata schema
          rule:   /properties/templates/items/properties/name/maxLength -> 120
          field:  /templates/129/name -> string: "Retrieve records for campaigns and their members from Salesf"...
      at Context.<anonymous> (test/template-metadata-schema-test.js:21:[36](https://github.com/ot4i/app-connect-templates/actions/runs/3955983945/jobs/6774755885#step:6:37))
      at processImmediate (internal/timers.js:464:21)
```
I have updated to full-fill the 120 characters requirement. 

From: 
Retrieve records for campaigns and their members from Salesforce and update the rows of the Microsoft Excel Online worksheet with campaign details

To:
Retrieve campaign-related records from Salesforce and update the rows in Microsoft Excel Online with campaign details

2023-02-15 16:16 UTC, AnimatIan requested changes
The links to the instructions in Github don't work. I think that they need to start with https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/ before the _instructions.md filename.
Please change the links in the _instructions.md files.

2023-02-16 14:42 UTC, shahminiaru commented
Updated.
- updated to include https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/

2023-02-20 16:48 UTC, AnimatIan submitted a review, later dismissed

2023-02-20 16:52 UTC, AnimatIan approved these changes

2023-02-20 16:53 UTC, merged