Amazon EventBridge shahmini master
ot4i/app-connect-templates pull request #283
Opened 2023-01-20 03:39 UTC by shahminiaru

UC1 (part1) Amazon EventBridge sends events whenever a Salesforce lead is successfully created or whenever a Salesforce lead creation fails

2023-01-20 04:04 UTC, shahminiaru commented
Imported to local SB:
![image](https://user-images.githubusercontent.com/86762255/213610852-6d546d7c-1041-4556-8a24-c77b9f588acc.png)

2023-02-15 16:06 UTC, AnimatIan requested changes
The links to the instructions in Github don't work. I think that they need to start with https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/ before the _instructions.md filename.
Please change the links in the _instructions.md files.

2023-02-16 14:39 UTC, shahminiaru commented
Updated. 
- updated to include https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/

2023-02-20 17:02 UTC, AnimatIan submitted a review, later dismissed

2023-02-20 17:05 UTC, AnimatIan approved these changes

2023-02-20 17:05 UTC, merged